name: 02 - Workflow Events
on: pull_request

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "Push event triggered this workflow"
