name: 06 - Contexts

run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

env: MY_WORKFLOW_VAR = "workflow"
  MY_OVERWRITTEN_VAR = "workflow"

jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      MY_JOB_VAR: "job"
      MY_OVERWRITTEN_VAR: "job"
    steps:
      - name: Display Information
        run: |
          echo "The event that triggered this job was a ${{ github.event_name }} event."
          echo "The branch that triggered this job is ${{ github.ref }}."
          echo "The SHA of the commit that triggered this job is ${{ github.sha }}."
          echo "The person who triggered this job is ${{ github.actor }}."
          echo "The name of the workflow that triggered this job is ${{ github.workflow }}."
          echo "The workflow run ID is ${{ github.run_id }}."
          echo "The workflow run number is ${{ github.run_number }}."
      - name: Retrieve Variable
        run: |
          echo "variable value: ${{ vars.MY_VAR }}"
      - name: Print Env Variables
        env: MY_OVERWRITTEN_VAR = "step"
        run: |
          echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
          echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
      - name: Print Env Variables
        run: |
          echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
          echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
